project:
  type: website

website:
  title: "quarto-playground"
  cookie-consent:
    type: express
    style: simple
    palette: dark
    policy-url: ""
  page-footer:
    left: Made with <3 and Quarto
    right:
      - icon: github
        href: https://github.com
      - icon: instagram
        href: https://www.instagram.com
      - icon: youtube
        href: https://www.youtube.com
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: blog.qmd
        text: blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true